create sequence cliente_seq start with 1 increment by 50;
create sequence dieta_seq start with 1 increment by 50;
create sequence entrenador_seq start with 1 increment by 50;
create sequence usuario_seq start with 1 increment by 50;
create table cliente (dieta_id integer, fecha_nacimiento date, id_usuario integer not null, direccion varchar(255), dni varchar(255), sexo varchar(255) check (sexo in ('HOMBRE','MUJER','OTRO')), telefono varchar(255), primary key (id_usuario));
create table dieta (duracion_dias integer, entrenador_id_usuario integer, id integer not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table entrenador (fecha_alta date, fecha_baja date, fecha_nacimiento date, id integer, id_usuario integer not null, direccion varchar(255), dni varchar(255), especialidad varchar(255), experiencia varchar(255), observaciones varchar(255), telefono varchar(255), titulacion varchar(255), primary key (id_usuario));
create table usuario (administrador boolean, id integer not null, apellido1 varchar(255), apellido2 varchar(255), email varchar(255), nombre varchar(255), password varchar(255), primary key (id));
alter table if exists cliente add constraint FKkj1m9f31egungnt19c0ahubt1 foreign key (dieta_id) references dieta;
alter table if exists dieta add constraint FKlansbcpql9gpaknbilase6oc9 foreign key (entrenador_id_usuario) references entrenador;
create sequence cliente_seq start with 1 increment by 50;
create sequence dieta_seq start with 1 increment by 50;
create sequence entrenador_seq start with 1 increment by 50;
create sequence usuario_seq start with 1 increment by 50;
create table cliente (dieta_id integer, fecha_nacimiento date, id_usuario integer not null, direccion varchar(255), dni varchar(255), sexo varchar(255) check (sexo in ('HOMBRE','MUJER','OTRO')), telefono varchar(255), primary key (id_usuario));
create table dieta (duracion_dias integer, entrenador_id_usuario integer, id integer not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table entrenador (fecha_alta date, fecha_baja date, fecha_nacimiento date, id integer, id_usuario integer not null, direccion varchar(255), dni varchar(255), especialidad varchar(255), experiencia varchar(255), observaciones varchar(255), telefono varchar(255), titulacion varchar(255), primary key (id_usuario));
create table usuario (administrador boolean, id integer not null, apellido1 varchar(255), apellido2 varchar(255), email varchar(255), nombre varchar(255), password varchar(255), primary key (id));
alter table if exists cliente add constraint FKkj1m9f31egungnt19c0ahubt1 foreign key (dieta_id) references dieta;
alter table if exists dieta add constraint FKlansbcpql9gpaknbilase6oc9 foreign key (entrenador_id_usuario) references entrenador;
create sequence cliente_seq start with 1 increment by 50;
create sequence dieta_seq start with 1 increment by 50;
create sequence entrenador_seq start with 1 increment by 50;
create sequence usuario_seq start with 1 increment by 50;
create table cliente (dieta_id integer, fecha_nacimiento date, id_usuario integer not null, direccion varchar(255), dni varchar(255), sexo varchar(255) check (sexo in ('HOMBRE','MUJER','OTRO')), telefono varchar(255), primary key (id_usuario));
create table dieta (duracion_dias integer, entrenador_id_usuario integer, id integer not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table entrenador (fecha_alta date, fecha_baja date, fecha_nacimiento date, id integer, id_usuario integer not null, direccion varchar(255), dni varchar(255), especialidad varchar(255), experiencia varchar(255), observaciones varchar(255), telefono varchar(255), titulacion varchar(255), primary key (id_usuario));
create table usuario (administrador boolean, id integer not null, apellido1 varchar(255), apellido2 varchar(255), email varchar(255), nombre varchar(255), password varchar(255), primary key (id));
alter table if exists cliente add constraint FKkj1m9f31egungnt19c0ahubt1 foreign key (dieta_id) references dieta;
alter table if exists dieta add constraint FKlansbcpql9gpaknbilase6oc9 foreign key (entrenador_id_usuario) references entrenador;
create sequence cliente_seq start with 1 increment by 50;
create sequence dieta_seq start with 1 increment by 50;
create sequence entrenador_seq start with 1 increment by 50;
create sequence usuario_seq start with 1 increment by 50;
create table cliente (dieta_id integer, fecha_nacimiento date, id_usuario integer not null, direccion varchar(255), dni varchar(255), sexo varchar(255) check (sexo in ('HOMBRE','MUJER','OTRO')), telefono varchar(255), primary key (id_usuario));
create table dieta (duracion_dias integer, entrenador_id_usuario integer, id integer not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table entrenador (fecha_alta date, fecha_baja date, fecha_nacimiento date, id integer, id_usuario integer not null, direccion varchar(255), dni varchar(255), especialidad varchar(255), experiencia varchar(255), observaciones varchar(255), telefono varchar(255), titulacion varchar(255), primary key (id_usuario));
create table usuario (administrador boolean, id integer not null, apellido1 varchar(255), apellido2 varchar(255), email varchar(255), nombre varchar(255), password varchar(255), primary key (id));
alter table if exists cliente add constraint FKkj1m9f31egungnt19c0ahubt1 foreign key (dieta_id) references dieta;
alter table if exists dieta add constraint FKlansbcpql9gpaknbilase6oc9 foreign key (entrenador_id_usuario) references entrenador;
create sequence cliente_seq start with 1 increment by 50;
create sequence dieta_seq start with 1 increment by 50;
create sequence entrenador_seq start with 1 increment by 50;
create sequence usuario_seq start with 1 increment by 50;
create table cliente (dieta_id integer, fecha_nacimiento date, id_usuario integer not null, direccion varchar(255), dni varchar(255), sexo varchar(255) check (sexo in ('HOMBRE','MUJER','OTRO')), telefono varchar(255), primary key (id_usuario));
create table dieta (duracion_dias integer, entrenador_id_usuario integer, id integer not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table entrenador (fecha_alta date, fecha_baja date, fecha_nacimiento date, id integer, id_usuario integer not null, direccion varchar(255), dni varchar(255), especialidad varchar(255), experiencia varchar(255), observaciones varchar(255), telefono varchar(255), titulacion varchar(255), primary key (id_usuario));
create table usuario (administrador boolean, id integer not null, apellido1 varchar(255), apellido2 varchar(255), email varchar(255), nombre varchar(255), password varchar(255), primary key (id));
alter table if exists cliente add constraint FKkj1m9f31egungnt19c0ahubt1 foreign key (dieta_id) references dieta;
alter table if exists dieta add constraint FKlansbcpql9gpaknbilase6oc9 foreign key (entrenador_id_usuario) references entrenador;
