create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
create sequence dieta_seq start with 1 increment by 50;
create table dieta (duracion_dias integer, entrenador bigint, id bigint not null, descripcion varchar(255), nombre varchar(255), objetivo varchar(255), observaciones varchar(255), recomendaciones varchar(255), alimentos varchar(255) array, primary key (id));
create table dieta_clientes (clientes bigint, dieta_id bigint not null);
alter table if exists dieta_clientes add constraint FKst73eerfaasmdsibku92bv5o5 foreign key (dieta_id) references dieta;
